version: '2'
services:
  log:
    image: goharbor/harbor-log:v1.6.3
    container_name: harbor-log 
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
      - {{ data_dir }}/harbor/common/config/log/:/etc/logrotate.d/:z
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - harbor
  registry:
    image: goharbor/registry-photon:v2.6.2-v1.6.3
    container_name: registry
    restart: always
    volumes:
      - {{ data_dir }}/harbor/data/registry:/storage:z
      - {{ data_dir }}/harbor/common/config/registry/:/etc/registry/:z
      - {{ data_dir }}/harbor/common/config/custom-ca-bundle.crt:/harbor_cust_cert/custom-ca-bundle.crt:z
    networks:
      - harbor
    environment:
      - GODEBUG=netdns=cgo
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
        #  postgresql:
        #    image: goharbor/harbor-db:v1.6.3
        #    container_name: harbor-db
        #    restart: always
        #    volumes:
        #      - {{ data_dir }}/harbor/data/database:/var/lib/postgresql/data:z
        #    networks:
        #      - harbor
        #    env_file:
        #      - {{ data_dir }}/harbor/common/config/db/env
        #    depends_on:
        #      - log
        #    logging:
        #      driver: "syslog"
        #      options:  
        #        syslog-address: "tcp://127.0.0.1:1514"
        #        tag: "postgresql"
  adminserver:
    image: goharbor/harbor-adminserver:v1.6.3
    container_name: harbor-adminserver
    env_file:
      - {{ data_dir }}/harbor/common/config/adminserver/env
    restart: always
    volumes:
      - {{ data_dir }}/harbor/data/config/:/etc/adminserver/config/:z
      - {{ data_dir }}/harbor/data/secretkey:/etc/adminserver/key:z
      - {{ data_dir }}/harbor/data/:/data/:z
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
  ui:
    image: goharbor/harbor-ui:v1.6.3
    container_name: harbor-ui
    env_file:
      - {{ data_dir }}/harbor/common/config/ui/env
    restart: always
    volumes:
      - {{ data_dir }}/harbor/common/config/ui/app.conf:/etc/ui/app.conf:z
      - {{ data_dir }}/harbor/common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
      - {{ data_dir }}/harbor/common/config/ui/certificates/:/etc/ui/certificates/:z
      - {{ data_dir }}/harbor/data/secretkey:/etc/ui/key:z
      - {{ data_dir }}/harbor/data/ca_download/:/etc/ui/ca/:z
      - {{ data_dir }}/harbor/data/psc/:/etc/ui/token/:z
    networks:
      - harbor
    depends_on:
      - log
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
    image: goharbor/harbor-jobservice:v1.6.3
    container_name: harbor-jobservice
    env_file:
      - {{ data_dir }}/harbor/common/config/jobservice/env
    restart: always
    volumes:
      - {{ data_dir }}/harbor/data/job_logs:/var/log/jobs:z
      - {{ data_dir }}/harbor/common/config/jobservice/config.yml:/etc/jobservice/config.yml:z
    networks:
      - harbor
    depends_on:
      - redis
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  redis:
    image: goharbor/redis-photon:v1.6.3
    container_name: redis
    restart: always
    volumes:
      - {{ data_dir }}/harbor/data/redis:/var/lib/redis
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "redis"
  proxy:
    image: goharbor/nginx-photon:v1.6.3
    container_name: nginx
    restart: always
    volumes:
      - {{ data_dir }}/harbor/common/config/nginx:/etc/nginx:z
    networks:
      - harbor
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
        #      - postgresql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false

