version: '2'
services:
  ui:
    networks:
      harbor-clair:
        aliases:
          - harbor-ui
  jobservice:
    networks:
      - harbor-clair
  registry:
    networks:
      - harbor-clair
        #  postgresql:
        #    networks:
        #      harbor-clair:
        #        aliases:
        #          - harbor-db
  clair:
    networks:
      - harbor-clair
    container_name: clair
    image: goharbor/clair-photon:v2.0.6-v1.6.3
    restart: always
    cpu_quota: 50000
    depends_on:
      - log 
    volumes:
      - {{ data_dir }}/harbor/common/config/clair/config.yaml:/etc/clair/config.yaml:z
      - {{ data_dir }}/harbor/common/config/custom-ca-bundle.crt:/harbor_cust_cert/custom-ca-bundle.crt:z
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair"
    env_file:
      {{ data_dir }}/harbor/common/config/clair/clair_env
networks:
  harbor-clair:
    external: false
