---
- name: Env Prepare - Install yum-utils
  yum: name=yum-utils state=present

- name: Env Prepare - Install device-mapper-persistent-data
  yum: name=device-mapper-persistent-data state=present

- name: Env Prepare - Install lvm2
  yum: name=lvm2 state=present

- name: Env Prepare - Docker-ce Repo Config
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install containerd.io
  yum: name=containerd.io state=present

- name: Install docker-ce
  yum: name=docker-ce-18.09.1 state=present

- name: Docker Config Dir Check
  file: path=/etc/docker/ state=directory

- name: Config Docker
  template: src=../docker-ce/daemon.json dest=/etc/docker/daemon.json

- name: Start Docker
  service: name=docker state=restarted enabled=yes
