---
- name: Install Postgresql yum repo
  copy: src=../postgresql/pgdg-11-centos.repo dest=/etc/yum.repos.d/ 
- name: Yum Makecache
  shell:  yum clean all && yum makecache

- name: Install Postgresql11 Client
  yum: name=postgresql11   state=present
- name: Install Postgresql11 Server
  yum: name=postgresql11-server state=present

- name: Postgresql11 Service File Config
  template: src=../postgresql/postgresql-11.service dest=/etc/systemd/system/postgresql-11.service force=true

- name: Postgresql11 Service DaemonReload
  shell: systemctl daemon-reload 

- name: Keepalive Script Dir
  file: path=/root/keepalived state=directory

- name: Copy Postgresql11 Master Change Script
  template: src=../postgresql/to_master.sh dest=/root/keepalived/to_master.sh force=true mode=0700

- import_tasks: ./postgresql/postgresql_master.yaml
  when: state == "MASTER"

- import_tasks: ./postgresql/postgresql_backup.yaml
  when: state == "BACKUP"


