apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  labels:
    alertmanager: main
spec:
  replicas: {{ alert_replicas }}
  baseImage: {{ base_image_addr }}/alertmanager
  version: ALERTMANAGER_VERSION
  externalUrl: ALERTMANAGER_EXTERNAL_URL
  nodeSelector:
    node_label_key: node_label_value
  priorityClassName: system-node-critical
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: MasterOnly
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 4096Mi
      cpu: 4000m
 
