---
- import_tasks: ./cni_install.yaml

  #- name: CNI Confifg File
  #  template: src=../network/cni/bridge/99-loopback.conf.template dest=/etc/cni/net.d/99-loopback.conf

- name: CNI Confifg File
  template: src=../network/cni/bridge/host-local/{{ inventory_hostname }} dest=/etc/cni/net.d/11-bridge.conf
  when:  bridge_host_local | default(False)

- name: CNI Confifg File
  template: src=../network/cni/bridge/11-bridge.conf.template.dhcp dest=/etc/cni/net.d/11-bridge.conf
  when:  bridge_dhcp | default(False)

- name: CNI0 interface config 
  template: src=../network/cni/bridge/ifcfg-cni0 dest=/etc/sysconfig/network-scripts/

- name: Phy interface config 
  template: src=../network/cni/bridge/ifcfg-xx dest=/etc/sysconfig/network-scripts/ifcfg-{{ container_if }}

- name: Restart Network
  shell: systemctl restart network

