---
- name: Flannel etcd Config 
  shell: echo "alias etcdctl2='export ETCDCTL_API=2 && etcdctl --endpoint=https://127.0.0.1:2379 --ca-file=/etc/kubernetes/ssl/ca.pem  --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem'" >> /root/.bashrc

- name: Flannel etcd Config Check
  shell: etcdctl --endpoint=https://127.0.0.1:2379 --ca-file=/etc/kubernetes/ssl/ca.pem  --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem  ls /kube-centos/network
  register: etcd_config
  ignore_errors: True

- name: Flannel etcd Config
  shell: etcdctl --endpoint=https://127.0.0.1:2379 --ca-file=/etc/kubernetes/ssl/ca.pem  --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem  mkdir /kube-centos/network
  when: etcd_config.rc != 0

- name: Flannel etcd Config Check
  shell: etcdctl --endpoint=https://127.0.0.1:2379 --ca-file=/etc/kubernetes/ssl/ca.pem  --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem  ls /kube-centos/network/config
  register: etcd_config
  ignore_errors: True

- name: Flannel etcd Config
  shell: etcdctl  --endpoint=https://127.0.0.1:2379 --ca-file=/etc/kubernetes/ssl/ca.pem  --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem   mk /kube-centos/network/config '{"Network":"{{ pod_network }}","SubnetLen":{{ pod_network_sublen }},"Backend":{"Type":"{{ network_type }}"}}'
  when: etcd_config.rc != 0
