[config]
vip = "{{ harbor_vip }}"
servers = ["HARBORIP_PLACEHOLDER", "HARBORIP_PLACEHOLDER"]

url_protocol = "{{ harbor_protocol }}"
username = "admin"
password = "Wocloud12345"

[log]
#PanicLevel=0
#FatalLevel=1
#ErrorLevel=2
#WarnLevel=3
#InfoLevel=4
#DebugLevel=5

loglevel=4
