apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-{{ pv_num }}
spec:
  storageClassName: prometheus-storage
  capacity:
    storage: {{ prometheus_data_size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ prometheus_data_path }}/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ node_name }}
