apiVersion: v1
kind: Endpoints
metadata:
  name: kube-controller-manager-prometheus
  namespace: kube-system
  labels:
    k8s-app: kube-controller-manager
subsets:
- ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
  addresses:
